### PR TITLE
Removed the unused tracks added previously

### PR DESCRIPTION
**Pull request by AmaurX**

### CODE REVIEW

**Comment by AmaurX** [comment]
@AndreaCensi , tagging you cause I cant assign you, sorry.

**Comment by AndreaCensi** [comment]
waiting for this as it would break existing code

**Comment by afdaniele** [comment]
@AndreaCensi @AmaurX 
What's the status on this?

**Comment by AndreaCensi** [comment]
@afdaniele I believe this can be closed as changes were added in a different PR

**Comment by afdaniele** [comment]
@AndreaCensi 
Sounds good, I don't have write access to this repo, so please, close it.

**Pull request closed without merging**
